// <auto-generated />
using System;
using Diva.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Diva.Api.Data.Migrations
{
    [DbContext(typeof(DivaDbContext))]
    [Migration("20261001071054_OrderPaidAt")]
    partial class OrderPaidAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("order_number_seq");

            modelBuilder.Entity("Diva.Api.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_customers_name");

                    b.HasIndex("Phone")
                        .HasDatabaseName("ix_customers_phone");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Diva.Api.Domain.LaundryService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("category");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MaxPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("max_price");

                    b.Property<decimal?>("MinQty")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("min_qty");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_services_sort_order");

                    b.ToTable("services", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000201"),
                            Category = "Laundry Kiloan",
                            IsActive = true,
                            MinQty = 3m,
                            Name = "Cuci Kering Setrika",
                            Price = 7000m,
                            SortOrder = 10,
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000202"),
                            Category = "Laundry Kiloan",
                            IsActive = true,
                            MinQty = 3m,
                            Name = "Cuci Kering Lipat",
                            Price = 5000m,
                            SortOrder = 20,
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000203"),
                            Category = "Bed Cover",
                            IsActive = true,
                            Name = "Bed Cover Single (S)",
                            Price = 30000m,
                            SortOrder = 30,
                            Unit = "Pcs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000204"),
                            Category = "Bed Cover",
                            IsActive = true,
                            Name = "Bed Cover Single (S) - Set",
                            Price = 45000m,
                            SortOrder = 40,
                            Unit = "Pcs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000205"),
                            Category = "Bed Cover",
                            IsActive = true,
                            Name = "Bed Cover Double (L)",
                            Price = 35000m,
                            SortOrder = 50,
                            Unit = "Pcs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000206"),
                            Category = "Bed Cover",
                            IsActive = true,
                            Name = "Bed Cover Double (L) - Set",
                            Price = 55000m,
                            SortOrder = 60,
                            Unit = "Pcs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000207"),
                            Category = "Bed Cover",
                            IsActive = true,
                            Name = "Bed Cover Big Size",
                            Price = 50000m,
                            SortOrder = 70,
                            Unit = "Pcs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000208"),
                            Category = "Bed Cover",
                            IsActive = true,
                            Name = "Bed Cover Big Size - Set",
                            Price = 70000m,
                            SortOrder = 80,
                            Unit = "Pcs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000209"),
                            Category = "Selimut",
                            IsActive = true,
                            Name = "Selimut Tipis/Bulu Ukuran Kecil",
                            Price = 25000m,
                            SortOrder = 90,
                            Unit = "Pcs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000210"),
                            Category = "Selimut",
                            IsActive = true,
                            Name = "Selimut Tipis/Bulu Ukuran Besar",
                            Price = 35000m,
                            SortOrder = 100,
                            Unit = "Pcs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000211"),
                            Category = "Karpet / Permadani",
                            IsActive = true,
                            MinQty = 4m,
                            Name = "Karpet Tipis",
                            Price = 15000m,
                            SortOrder = 110,
                            Unit = "M2"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000212"),
                            Category = "Karpet / Permadani",
                            IsActive = true,
                            MinQty = 4m,
                            Name = "Karpet Sedang",
                            Price = 20000m,
                            SortOrder = 120,
                            Unit = "M2"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000213"),
                            Category = "Karpet / Permadani",
                            IsActive = true,
                            MinQty = 4m,
                            Name = "Karpet Tebal",
                            Price = 25000m,
                            SortOrder = 130,
                            Unit = "M2"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000214"),
                            Category = "Laundry Satuan",
                            IsActive = true,
                            Name = "Atasan (Kemeja/Blus/Batik/T-Shirt)",
                            Price = 25000m,
                            SortOrder = 140,
                            Unit = "Pcs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000215"),
                            Category = "Laundry Satuan",
                            IsActive = true,
                            Name = "Bawahan (Celana/Rok/Jeans)",
                            Price = 25000m,
                            SortOrder = 150,
                            Unit = "Pcs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000216"),
                            Category = "Pakaian Formal",
                            IsActive = true,
                            Name = "Jas/Blazer",
                            Price = 35000m,
                            SortOrder = 160,
                            Unit = "Pcs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000217"),
                            Category = "Pakaian Formal",
                            IsActive = true,
                            Name = "Setelan Jas (Jas + Celana)",
                            Price = 60000m,
                            SortOrder = 170,
                            Unit = "Pcs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000218"),
                            Category = "Dress / Gaun",
                            IsActive = true,
                            Name = "Dress Pendek/Gaun Standard (Polos)",
                            Price = 40000m,
                            SortOrder = 180,
                            Unit = "Pcs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000219"),
                            Category = "Dress / Gaun",
                            IsActive = true,
                            MaxPrice = 150000m,
                            Name = "Dress Pesta/Kebaya Payet",
                            Price = 60000m,
                            SortOrder = 190,
                            Unit = "Pcs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000220"),
                            Category = "Dress / Gaun",
                            IsActive = true,
                            Name = "Dress Baju Muslim Polos",
                            Price = 50000m,
                            SortOrder = 200,
                            Unit = "Pcs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000221"),
                            Category = "Dress / Gaun",
                            IsActive = true,
                            Name = "Dress Baju Muslim Variasi",
                            Price = 75000m,
                            SortOrder = 210,
                            Unit = "Pcs"
                        });
                });

            modelBuilder.Entity("Diva.Api.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("order_number");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payment_status");

                    b.Property<string>("PublicToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("public_token");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_orders_created_at");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_orders_customer_id");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_order_number");

                    b.HasIndex("PaidAt")
                        .HasDatabaseName("ix_orders_paid_at");

                    b.HasIndex("PublicToken")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_public_token");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_orders_status");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Diva.Api.Domain.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BilledQty")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("billed_qty");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer")
                        .HasColumnName("line_no");

                    b.Property<decimal?>("MinQty")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("min_qty");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<decimal>("Qty")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("qty");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("service_name");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("unit");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_order_items_service_id");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("Diva.Api.Domain.OutletProfile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("ReceiptFooter")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("receipt_footer");

                    b.HasKey("Id")
                        .HasName("pk_outlet_profile");

                    b.ToTable("outlet_profile", null, t =>
                        {
                            t.HasCheckConstraint("ck_outlet_profile_singleton", "id = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "DIVA Laundry",
                            ReceiptFooter = "Terima kasih telah mempercayakan cucian Anda kepada kami."
                        });
                });

            modelBuilder.Entity("Diva.Api.Domain.Order", b =>
                {
                    b.HasOne("Diva.Api.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Diva.Api.Domain.OrderItem", b =>
                {
                    b.HasOne("Diva.Api.Domain.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");

                    b.HasOne("Diva.Api.Domain.LaundryService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_services_service_id");

                    b.Navigation("Order");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Diva.Api.Domain.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
